# These two props required due to res IDs in switch statements.  Need to refactor for gradle 10.
android.nonFinalResIds=false
android.enableAppCompileTimeRClass=false
# Needed because we don't fully qualify all R references in the codebase (com.gpl.rpg.AndorsTrail.R.id... )
android.enableNonTransitiveRClass=false